image:https://img.shields.io/clojars/v/pfeodrippe/recife.svg[link="http://clojars.org/pfeodrippe/recife",title="Clojars Project"]


= Recife

A model checker library in Clojure.

See a quick video with new features of 0.3.0 at https://www.youtube.com/watch?v=C9WwF4RXq74.

== Usage

We will use the following aliases during the documentation.

----
(require '[recife.core :as r]
         '[recife.anim :as ra])
----

Our mains macros/functions are

- `r/defproc`, you define processes and steps;
- `r/definvariant`, you define an invariant to be tested;
- `r/defproperty`, you define a temporal property, this is really powerful as it
  can check if something will happen (e.g. if the process will terminate or if
  it will eventually send the request).
- `r/run-model`, you run the model checker passing a global state (just a clojure
  map) and the vars defined with `r/def.*`;
- `r/done`, you state that the process is done;
- `r/goto`, go to another step in the same process (some step defined in the
  context of the `r/defproc`).
- `ra/visualize-result` to see the result in a graphic format (we use `Quil` to
  draw stuff).

See the tests to check what's available, there are more advanced concepts like
fairness there.

Open an Issue or reach out to me on https://twitter.com/pfeodrippe[Twitter].

== Analyzer

Test your implementation using `recife.analyzer/analyzer`, think of it like property
base testing, but driven by the traces your model checker result generate.

See link:test/example/implementation/wire_1.clj#L118[example].

== How it works

It uses TLA+/TLC behind the scenes, which is a very powerful model checker where
you can verify specifications.

Instead of having to learn a new language (which I would incentivize because TLA+
is a great one), we can use normal Clojure code (it makes heavy use of TLC
overrides).

It calls TLC through a new JVM, so you have to create your vars outside of, e.g., a comment form.
Also don't put your `r/run-model` call in the wild so it's not called again
when on the new JVM (NOTE: make `r/run-model` ignore it by using a JVM property).

== WARNING!!

This is a alpha library, use at your own risk, file bugs and issues.

See examples at `test/hillel` folder and `test/hillel_tests.clj` file.

== Related Projects or of Interest
- https://www.stateright.rs/getting-started.html[Stateright].
- https://github.com/tlaplus/tlaplus[TLA+/TLC].
