image:https://img.shields.io/clojars/v/pfeodrippe/recife.svg[link="http://clojars.org/pfeodrippe/recife",title="Clojars Project"]


= Recife

A model checker library in Clojure.

== Usage

We will use the following aliases during the documentation.

----
(require '[recife.core :as r]
         '[recife.anim :as ra])
----

Our mains macros/functions are

- `r/defproc`, you define processes and steps;
- `r/definvariant`, you define an invariant to be tested;
- `r/defproperty`, you define a temporal property, this is really powerful as it
  can check if something will happen (e.g. if the process will terminate or if
  the ).
- `r/run-model`, you run the model checker passing a global state (just a clojure
  map) and the vars defined with `r/def.*`;
- `r/done`, you state that the process is done;
- `r/goto`, go to another step in the same process (some step defined in the
  context of the `r/defproc`).

== How it works

It uses TLA+/TLC behind the scenes, which is a very powerful model checker where
you can verify specifications.

Instead of having to learn a new language (which I would incentivize because TLA+
is a great one), we can use normal Clojure code (it makes heavy use of TLC
overrides).

== WARNING!!

This is a alpha library, use at your own risk, file bugs and issues.

See examples at `test/hillel` folder and `test/hillel_tests.clj` file.
